apiVersion: v1
kind: Pod
metadata:
  name: prom-demo
spec:
  containers:
    - name: prom-demo
      image: prom/prometheus
      volumeMounts:
      - name: config-volume
        mountPath: /etc/prometheus
  volumes:
    - name: config-volume
      configMap:
        name: prom-config
  restartPolicy: Never